### ISSUE TITLE
GoogleSignInAccount must not be null

### ISSUE THREAD

**Issue by mimouni** [princesanjivy/cordova-plugin-leaderboard#1]
after the call to leaderboard.init(...);  

the game still not signed in.

implementation 'com.google.android.gms:play-services-base:17.5.0'
    implementation 'com.google.android.gms:play-services-ads:19.6.0'
    implementation 'com.google.android.gms:play-services-games:21.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.0.0'

**Comment by princesanjivy** [comment]
Check whether the APP_ID is set properly.
You need to build the app (signed) and link it to Play Games Console.

If you've any queries please let me know!

**Comment by mimouni** [comment]
I've verified APP_ID it's set.

contact me if possible at : mimouni@outlook.com

**Comment by princesanjivy** [comment]
Plugin works fine for me and I've tested it many times. It would be more clear if you show me the logs.

**Comment by mimouni** [comment]
I created a simple project to make tests : 

index.js file : 
========

<pre>document.addEventListener('deviceready', onDeviceReady, false);

signed = false;
leaderboard_id = 'CgkIgcPSsYgcEAIQAA';
score = 0;

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    document.getElementById('deviceready').classList.add('ready');
	
	leaderboard.init(
		function(){
			// on sign in success;
			signed = true;
			console.log('++++++ leaderboard signed in .....');
		},
		function(){
			// on failure ;
			signed = false;
			console.log('++++++ leaderboard error .....');
		}
	);
}

function setScore(){
	score = score + 10;
	leaderboard.setScore(
		  leaderboard_id, // Leaderboard id
		  score, // score to be submitted to that leaderboard
		  function(){}, //successCallback
		  function(){} // errorCallback
	);
}

function showLeaderboard(){
	leaderboard.showLeaderboard(
		leaderboard_id, // Leaderboard id
		function(){}, // successCallback
		function(){} // errorCallback
	);
}

</pre>

index.html file :  
==========
<pre>

<`button onclick="setScore()"`>Set Score<`/button`>
<`button onclick="showLeaderboard()"`>Show Leaderboard<`/button`>

</pre>


Logs :  
=====

`W/PluginManager: THREAD WARNING: exec() call to Leaderboard.init blocked the main thread for 155ms. Plugin should use CordovaInterface.getThreadPool().
D/ViewRootImpl@8529202[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport: Input channel constructed: fd=131
D/ViewRootImpl@d5c7d61[SignInHubActivity]: setView = DecorView@89b2086[SignInHubActivity] TM=true MM=false
D/ViewRootImpl@d5c7d61[SignInHubActivity]: dispatchAttachedToWindow
V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@d5c7d61[SignInHubActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][720,1280] result=0x7 surface={valid=true 3290943488} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/OpenGLRenderer: eglCreateWindowSurface = 0xc1bcfca0
D/ViewRootImpl@8529202[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
D/ViewRootImpl@d5c7d61[SignInHubActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
D/ViewRootImpl@d5c7d61[SignInHubActivity]: MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@dd90974 nm : com.jacob.game ic=null
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=133
    Input channel destroyed: fd=104
D/ViewRootImpl@8529202[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={valid=true 3295670272} changed=false
D/ViewRootImpl@d5c7d61[SignInHubActivity]: MSG_WINDOW_FOCUS_CHANGED 0
I/zygote: Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()
I/zygote: Do partial code cache collection, code=56KB, data=62KB
    After code cache collection, code=56KB, data=62KB
    Increasing code cache capacity to 256KB
D/InputTransport: Input channel destroyed: fd=133
D/ViewRootImpl@d5c7d61[SignInHubActivity]: MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@4f8bf12 nm : com.jacob.game ic=null
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=132
D/ViewRootImpl@d5c7d61[SignInHubActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@8529202[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@20d06e3 nm : com.jacob.game ic=null
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=118
    Input channel destroyed: fd=132
D/CordovaActivity: Incoming Result. Request code = 9001
D/CordovaInterfaceImpl: Sending activity result to plugin
D/CordovaActivity: Resumed the activity.
D/ViewRootImpl@8529202[MainActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={valid=true 3295670272} changed=false
D/OpenGLRenderer: eglDestroySurface = 0xc1bcfca0
D/ViewRootImpl@d5c7d61[SignInHubActivity]: Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@d5c7d61[SignInHubActivity]: dispatchDetachedFromWindow
D/InputEventReceiver: channel '8a7c4a3 com.jacob.game/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~ Disposing input event receiver.
    channel '8a7c4a3 com.jacob.game/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~NativeInputEventReceiver.
D/InputTransport: Input channel destroyed: fd=131


I/zygote: Do full code cache collection, code=126KB, data=107KB
I/zygote: After code cache collection, code=116KB, data=91KB
D/ViewRootImpl@8529202[MainActivity]: ViewPostIme pointer 1
E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: GoogleSignInAccount must not be null
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.4.0:11)
        at com.google.android.gms.games.Games.getLeaderboardsClient(com.google.android.gms:play-services-games@@21.0.0:53)
        at com.princewebstudio.plugin.Leaderboard.setScore(Leaderboard.java:76)
        at com.princewebstudio.plugin.Leaderboard.execute(Leaderboard.java:59)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
`

I can pay to sponsor and resolve this problem.
mimouni@outlook.com

**Comment by princesanjivy** [comment]
Do you get this exception during runtime??

**Comment by princesanjivy** [comment]
Do you get this exception during runtime?

PS: accidently closed the issue.

**Comment by mimouni** [comment]
Thank you for your time and your support :) 

Yes during runtime.,

I got the error : 
java.lang.NullPointerException: GoogleSignInAccount must not be null

also, normally when I make a call to leaderboard.init(...);  the function call back is not returning.

I've already verified the app_id and the leaderboard id.
